-- Modelo fisico del esquema Salud Chilecito.
-- Ejecutar conectado como usuario salud.

CREATE TABLE especialidad (
  id_especialidad NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(100) NOT NULL,
  descripcion CLOB,
  activa CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_especialidad PRIMARY KEY (id_especialidad),
  CONSTRAINT uk_especialidad_nombre UNIQUE (nombre),
  CONSTRAINT ck_especialidad_activa CHECK (activa IN ('S', 'N'))
) TABLESPACE tbs_salud_data;

CREATE TABLE centro_salud (
  id_centro NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(150) NOT NULL,
  direccion VARCHAR2(200) NOT NULL,
  distrito VARCHAR2(100) NOT NULL,
  telefono VARCHAR2(40),
  tipo VARCHAR2(30) NOT NULL,
  email VARCHAR2(120),
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_centro_salud PRIMARY KEY (id_centro),
  CONSTRAINT uk_centro_nombre_distrito UNIQUE (nombre, distrito),
  CONSTRAINT ck_centro_tipo CHECK (tipo IN ('PUBLICO', 'PRIVADO', 'MIXTO')),
  CONSTRAINT ck_centro_activo CHECK (activo IN ('S', 'N'))
) TABLESPACE tbs_salud_data;

CREATE TABLE centro_especialidad (
  id_centro NUMBER NOT NULL,
  id_especialidad NUMBER NOT NULL,
  precio_base NUMBER(12, 2) DEFAULT 0 NOT NULL,
  requiere_derivacion CHAR(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT pk_centro_especialidad PRIMARY KEY (id_centro, id_especialidad),
  CONSTRAINT fk_ce_centro FOREIGN KEY (id_centro) REFERENCES centro_salud (id_centro),
  CONSTRAINT fk_ce_especialidad FOREIGN KEY (id_especialidad) REFERENCES especialidad (id_especialidad),
  CONSTRAINT ck_ce_derivacion CHECK (requiere_derivacion IN ('S', 'N')),
  CONSTRAINT ck_ce_precio CHECK (precio_base >= 0)
) TABLESPACE tbs_salud_data;

CREATE TABLE medico (
  id_medico NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(120) NOT NULL,
  matricula VARCHAR2(50) NOT NULL,
  telefono VARCHAR2(40),
  email VARCHAR2(120),
  id_especialidad NUMBER NOT NULL,
  id_centro NUMBER NOT NULL,
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_medico PRIMARY KEY (id_medico),
  CONSTRAINT uk_medico_matricula UNIQUE (matricula),
  CONSTRAINT fk_medico_especialidad FOREIGN KEY (id_especialidad) REFERENCES especialidad (id_especialidad),
  CONSTRAINT fk_medico_centro FOREIGN KEY (id_centro) REFERENCES centro_salud (id_centro),
  CONSTRAINT ck_medico_activo CHECK (activo IN ('S', 'N'))
) TABLESPACE tbs_salud_data;

CREATE TABLE paciente (
  id_paciente NUMBER GENERATED BY DEFAULT AS IDENTITY,
  dni VARCHAR2(20) NOT NULL,
  nombre VARCHAR2(120) NOT NULL,
  fecha_nacimiento DATE,
  telefono VARCHAR2(40),
  email VARCHAR2(120),
  obra_social VARCHAR2(100),
  distrito VARCHAR2(100),
  fecha_alta DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_paciente PRIMARY KEY (id_paciente),
  CONSTRAINT uk_paciente_dni UNIQUE (dni)
) TABLESPACE tbs_salud_data;

CREATE TABLE agenda_medico (
  id_agenda NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_medico NUMBER NOT NULL,
  dia_semana VARCHAR2(15) NOT NULL,
  hora_inicio VARCHAR2(5) NOT NULL,
  hora_fin VARCHAR2(5) NOT NULL,
  duracion_minutos NUMBER(3) DEFAULT 30 NOT NULL,
  cupo_diario NUMBER(3) DEFAULT 16 NOT NULL,
  CONSTRAINT pk_agenda_medico PRIMARY KEY (id_agenda),
  CONSTRAINT fk_agenda_medico FOREIGN KEY (id_medico) REFERENCES medico (id_medico),
  CONSTRAINT ck_agenda_dia CHECK (dia_semana IN ('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO')),
  CONSTRAINT ck_agenda_duracion CHECK (duracion_minutos BETWEEN 10 AND 120),
  CONSTRAINT ck_agenda_cupo CHECK (cupo_diario > 0)
) TABLESPACE tbs_salud_data;

CREATE TABLE turno (
  id_turno NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_paciente NUMBER NOT NULL,
  id_medico NUMBER NOT NULL,
  id_centro NUMBER NOT NULL,
  fecha_turno DATE NOT NULL,
  estado VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  precio_consulta NUMBER(12, 2) DEFAULT 0 NOT NULL,
  observaciones CLOB,
  creado_en DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_turno PRIMARY KEY (id_turno),
  CONSTRAINT fk_turno_paciente FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente),
  CONSTRAINT fk_turno_medico FOREIGN KEY (id_medico) REFERENCES medico (id_medico),
  CONSTRAINT fk_turno_centro FOREIGN KEY (id_centro) REFERENCES centro_salud (id_centro),
  CONSTRAINT ck_turno_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADO', 'ATENDIDO', 'CANCELADO', 'AUSENTE')),
  CONSTRAINT ck_turno_precio CHECK (precio_consulta >= 0)
) TABLESPACE tbs_salud_data;

CREATE TABLE historial_clinico (
  id_historial NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_paciente NUMBER NOT NULL,
  id_turno NUMBER,
  fecha_registro DATE DEFAULT SYSDATE NOT NULL,
  diagnostico VARCHAR2(300),
  indicaciones CLOB,
  profesional VARCHAR2(120),
  CONSTRAINT pk_historial_clinico PRIMARY KEY (id_historial),
  CONSTRAINT fk_historial_paciente FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente),
  CONSTRAINT fk_historial_turno FOREIGN KEY (id_turno) REFERENCES turno (id_turno)
) TABLESPACE tbs_salud_data;

CREATE TABLE documento_paciente (
  id_documento NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_paciente NUMBER NOT NULL,
  tipo_documento VARCHAR2(40) NOT NULL,
  nombre_archivo VARCHAR2(180) NOT NULL,
  contenido BLOB,
  url_externa VARCHAR2(500),
  creado_en DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_documento_paciente PRIMARY KEY (id_documento),
  CONSTRAINT fk_documento_paciente FOREIGN KEY (id_paciente) REFERENCES paciente (id_paciente),
  CONSTRAINT ck_documento_tipo CHECK (tipo_documento IN ('ORDEN', 'ESTUDIO', 'RECETA', 'IMAGEN', 'OTRO'))
) TABLESPACE tbs_salud_data;

CREATE TABLE auditoria_turno (
  id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_turno NUMBER NOT NULL,
  estado_anterior VARCHAR2(20),
  estado_nuevo VARCHAR2(20) NOT NULL,
  usuario VARCHAR2(80) DEFAULT USER NOT NULL,
  fecha_cambio DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_auditoria_turno PRIMARY KEY (id_auditoria),
  CONSTRAINT fk_auditoria_turno FOREIGN KEY (id_turno) REFERENCES turno (id_turno)
) TABLESPACE tbs_salud_data;
