-- Nuevas tablas para el modelo de hospital unico con seleccion por sintomas
-- Ejecutar conectado como usuario salud

-- Tabla de sintomas y su mapeo a especialidades
CREATE TABLE sintoma (
  id_sintoma NUMBER GENERATED BY DEFAULT AS IDENTITY,
  descripcion VARCHAR2(200) NOT NULL,
  id_especialidad NUMBER NOT NULL,
  prioridad VARCHAR2(20) DEFAULT 'MEDIA' NOT NULL,
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_sintoma PRIMARY KEY (id_sintoma),
  CONSTRAINT fk_sintoma_especialidad FOREIGN KEY (id_especialidad) REFERENCES especialidad (id_especialidad),
  CONSTRAINT ck_sintoma_prioridad CHECK (prioridad IN ('BAJA', 'MEDIA', 'ALTA', 'URGENTE')),
  CONSTRAINT ck_sintoma_activo CHECK (activo IN ('S', 'N'))
) TABLESPACE tbs_salud_data;

-- Tabla de configuracion del hospital (para instancias individuales)
CREATE TABLE configuracion_hospital (
  id_configuracion NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre_hospital VARCHAR2(150) NOT NULL,
  logo_url VARCHAR2(500),
  color_primario VARCHAR2(7) DEFAULT '#0066cc',
  color_secundario VARCHAR2(7) DEFAULT '#ffffff',
  mensaje_bienvenida CLOB,
  requiere_derivacion CHAR(1) DEFAULT 'N' NOT NULL,
  tiempo_cancelacion_horas NUMBER(3) DEFAULT 24,
  id_centro_principal NUMBER NOT NULL,
  CONSTRAINT pk_configuracion_hospital PRIMARY KEY (id_configuracion),
  CONSTRAINT fk_config_centro FOREIGN KEY (id_centro_principal) REFERENCES centro_salud (id_centro),
  CONSTRAINT ck_config_derivacion CHECK (requiere_derivacion IN ('S', 'N')),
  CONSTRAINT ck_config_tiempo CHECK (tiempo_cancelacion_horas BETWEEN 1 AND 168)
) TABLESPACE tbs_salud_data;

-- Tabla de tipos de consulta y sus rangos de precio
CREATE TABLE tipo_consulta (
  id_tipo_consulta NUMBER GENERATED BY DEFAULT AS IDENTITY,
  nombre VARCHAR2(100) NOT NULL,
  descripcion CLOB,
  duracion_minutos NUMBER(3) DEFAULT 30 NOT NULL,
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_tipo_consulta PRIMARY KEY (id_tipo_consulta),
  CONSTRAINT ck_tipo_consulta_activo CHECK (activo IN ('S', 'N')),
  CONSTRAINT ck_tipo_consulta_duracion CHECK (duracion_minutos BETWEEN 10 AND 120)
) TABLESPACE tbs_salud_data;

-- Tabla de precios por especialidad y tipo de consulta
CREATE TABLE precio_especialidad (
  id_precio NUMBER GENERATED BY DEFAULT AS IDENTITY,
  id_centro NUMBER NOT NULL,
  id_especialidad NUMBER NOT NULL,
  id_tipo_consulta NUMBER NOT NULL,
  precio_minimo NUMBER(12, 2) NOT NULL,
  precio_maximo NUMBER(12, 2) NOT NULL,
  precio_estimado NUMBER(12, 2) NOT NULL,
  activo CHAR(1) DEFAULT 'S' NOT NULL,
  CONSTRAINT pk_precio_especialidad PRIMARY KEY (id_precio),
  CONSTRAINT fk_precio_centro FOREIGN KEY (id_centro) REFERENCES centro_salud (id_centro),
  CONSTRAINT fk_precio_especialidad FOREIGN KEY (id_especialidad) REFERENCES especialidad (id_especialidad),
  CONSTRAINT fk_precio_tipo_consulta FOREIGN KEY (id_tipo_consulta) REFERENCES tipo_consulta (id_tipo_consulta),
  CONSTRAINT ck_precio_activo CHECK (activo IN ('S', 'N')),
  CONSTRAINT ck_precio_rango CHECK (precio_minimo <= precio_estimado AND precio_estimado <= precio_maximo)
) TABLESPACE tbs_salud_data;

-- Indices para optimizar consultas
CREATE INDEX idx_sintoma_especialidad ON sintoma(id_especialidad);
CREATE INDEX idx_sintoma_activo ON sintoma(activo);
CREATE INDEX idx_precio_especialidad_centro ON precio_especialidad(id_centro, id_especialidad);
CREATE INDEX idx_precio_especialidad_tipo ON precio_especialidad(id_tipo_consulta);

COMMIT;
